### ISSUE TITLE
MS19 Lasair LSST simulated system (receive and process simulated stream)

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lasair-project-management#167]
As listed in milestones spreadsheet : 

| Associated WP | Means of verification |
|--|--|
|  WP2.3 | "LASAIR can receive and process LSST Prompt Product simulated alert-stream"|

Work to attain this milestone
- [x] Put simulated alerts into Lasair Kafka system 
- [x] Modify ingest code to read these alerts
- [x] Set up DB/file system to store alerts 
- [x] Investigate how Lasair ZTF needs to be modified for LSST

**Comment by tms-epcc** [comment]
- Change request [C036](https://lsst-uk.atlassian.net/wiki/download/attachments/751108134/C036_Lasair_scope_redefine.pdf?api=v2) approved at 01/MAR/22 Exec
- title changed from “Infrastructure for LASAIR set up and operation" to "Lasair LSST simulated system (receive and process simulated stream)"
- scope and means of verification changed accordingly

**Comment by tms-epcc** [comment]
22/JUN/22
- @RoyWilliams reported that  @gpfrancis  has put the simulated alerts into Lasair Kafka stream, see [ELASTICC alerts for lasair-dev#15](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair4/15)

**Comment by tms-epcc** [comment]
29/SEP/22
- @tms-epcc emailed @andyxerxes @RoyWilliams and @smarttgit for help completing the change request to move the due date by four months

**Comment by tms-epcc** [comment]
12/OCT/22
- change request C053 submitted to the 08/NOV/22 Exec meeting for consideration.
- the change request is to delay the milestone due date by 4 months from 31/AUG/22 (PM38).  to 31/DEC/22 (PM42).

**Comment by tms-epcc** [comment]
09/NOV/22
- Change request [C053](https://lsst-uk.atlassian.net/wiki/download/attachments/751108134/C053_Delay_MS19.pdf?api=v2) approved at 08/NOV/22 Exec meeting.
- Change request moves due date from PM38 (31/AUG/22) to PM42 (31/DEC/22)

**Comment by tms-epcc** [comment]
14/DEC/22
- @RoyWilliams reported that items listed in work to attain the milestone have been met 
- will provide evidence in some form

**Comment by tms-epcc** [comment]
- Submitted to 23/JAN/23 Exec Group with recommendation to be marked as passed as well as evidence

**Comment by tms-epcc** [comment]
02/FEB/23
- No objections from Exec, milestone PASSED.
