### ISSUE TITLE
MS25 Lasair 4.0 release: enhanced technology and functionality

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lasair-project-management#173]
As listed in the milestones spreadsheet:
- associated WP: WP3.2
- Means of verification :  Astronomers access LASAIR via web interface, streams and API, ensuring the enhanced technology and functionality works

According to the version plan  in the [revised top-level plan ](https://lsst-uk.atlassian.net/wiki/download/attachments/758874134/Lasair-TLP-2022-03-09.pdf?api=v2) this version is 

| Version | Date | URL | input | access | hardware |  technology | functionality | 
|--------|-----|----|------|-------|-----------|------------|--------------|
|  4.0       | Jun'22 | lasair | ZTF | public | new-IRIS | scalable | improved |

Work to attain this milestone
- [x] Set up Lasair 4.0 infrastructure 
- [x] Acceptance testing 
- [x] Move data from old system
- [x] change domain name 
- [x] inform users service is live
- [x] Verification check

**Comment by tms-epcc** [comment]
Note this was renamed from MS17 since there already was an MS17

**Comment by tms-epcc** [comment]
- Change request [C036](https://lsst-uk.atlassian.net/wiki/download/attachments/751108134/C036_Lasair_scope_redefine.pdf?api=v2) approved at 01/MAR/22 Exec meeting
- Title changed from  “LASAIR Version 4.0 launched, with final web interface
and incorporating user documentation” to “Lasair 4.0 release:
enhanced technology and functionality
- Scope changed accordingly
- Means of verification changed from "Astronomers access LASAIR via web interface, and browse user documentation" to "Astronomers access LASAIR via web interface, streams and API, ensuring the enhanced technology and functionality works”.
- Due date changed from  PM33 (31/MAR/22) to PM36 (30/JUN/22).

**Comment by tms-epcc** [comment]
22/JUN/22
- the intention is still for this to be lasair-ztf but if necessary lasair-iris

**Comment by RoyWilliams** [comment]
https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2954461185/Lasair+System+Tests

**Comment by tms-epcc** [comment]
23/AUG/22
- @chrisfrohmaier is undertaking the milestone verification as part of [WP3.3 issue 27](https://app.zenhub.com/workspaces/lsstuk-project-mgmnt-5ee3ae947fc4e92804a2c64a/issues/lsst-uk/spectro-class-transients-wp3.3/27)

**Comment by tms-epcc** [comment]
29/SEP/22
- @chrisfrohmaier emailed @tms-epcc saying 
- "Ken (@genghisken)and I just had a good 20-minute chat about all things Lasair, including how I use it. I confirmed that all my code that interfaces with Lasair still works and my streams are still running. I’m also happy that all the all the enhanced functionality works.  
I’m satisfied that Lasair has met this milestone."

**Comment by tms-epcc** [comment]
30/SEP/22
- Exec group approved recommendation for Milestone being marked as passed.
