### ISSUE TITLE
Porting Lasair to new hardware (i.e. Somerville)

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lasair-project-management#255]
- [x] [Build porting plan](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2786164737), understand what is time critical, assign tasks
- [x] Build ingestion pipeline on new hardware
- [x] Build history files with 4 years data
- [x] Start ingestion
- [x] Ingest history files
- [x] Cleaning up

**Comment by tms-epcc** [comment]
05/OCT/22
- @RoyWilliams confirmed this is now complete.  
- Lasair has been in operation on new Somerville since summer'22
