### ISSUE TITLE
Lasair Cycle-8 April'23 to Sept'23

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lasair-project-management#284]
As taken from [Lasair Cycle-8 wiki planning page](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3161882625/Laser+Cycle+8+plan)
See also [notes from 29/MAR/23 Lasair fortnightly meeting](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3167485953/29+March+2023)

**Top Level goals this cycle**
- port Lasair to LSST
- deliver Lasair 5.0 on sim-stream data ([D3.5.1](https://app.zenhub.com/workspaces/lasair-62fcaf02d9b97057d4456a7b/issues/gh/lsst-uk/lasair-project-management/285))
- make new long term plan 

**Activities this cycle**
The tasks needed to deliver the above can be broken down into must-do and stretch goals.

**Must do**
- [x] Rebuild Lasair from ZTF to LSST
    - Convert LSST schema document to Lasair’s tables, with schema evolution
    - Define Lasair feature set in addition to LSST lightcurve features
    - Rebuild ingest/filter pipeline and Cassandra/Galera to work with LSST tables
- [x]  Deliver Lasair 5.0 - See ([D3.5.1](https://app.zenhub.com/workspaces/lasair-62fcaf02d9b97057d4456a7b/issues/gh/lsst-uk/lasair-project-management/285))
    - Ingest existing simstream by file and by kafka, with added features
    - Rebuild website to show LSST simstream data
- [x] Maintain Lasair ZTF
    - Respond to bugs and user questions
    - Apply code patches as required
    - Debate future for lasair-ztf (will conclude in C9)
- [x] Port lasair-deploy from Heat --> Terraform (see #294)
- Start performance testing (see #258)
    - Test alert distribution system works! Delivers 40-70 alerts per second.
    - Build performance-testing cluster
    - Build on performance testing plan and start implementation and measurement
- [x] Deliver new long-term plan for Phase C @andyxerxes (see #285)
    - Set up first draft on Overleaf based on LSST:UK Phase C plan
    - Hold brainstorm session to debate options
    - Complete plan
    
**Later Addition**
- [x] Oxford User Meeting, Sept'23 (see #297)

**Stretch goals**

- [x] Create new features for early explosive transients (see #278)
    - Fitting exp-bazin-blackbody models
    - From Fastfinder
- Build infrastructure for Gravitational Waves
- Upgrade Sherlock with S hemisphere catalog
- DELVE -- dark energy camera (what about it?)
- Cassandra integration tests
- Checking the monitoring of tests (added post 11/MAY/23 Lasair SE meeting)
- Issuing of alerts from Grafana monitoring (added post 11/MAY/23 Lasair SE meeting)
