### ISSUE TITLE
Lasair Cycle-9 Oct'23 to March'24

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lasair-project-management#303]
As taken from [Lasair Cycle-9 wiki planning page](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3271491585/Lasair+Cycle+9+plan)
See also notes from [04/OCT/23 Lasair fortnightly meeting](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3280240641)

In order of priority, the Activities, deliverables and milestones agreed as due in this cycle 

- [x] 1. Put cutouts in Cassandra
   - [x] a. [Code to read and write Cassandra cutouts](https://github.com/lsst-uk/lasair-lsst/issues/78). See also [PR](https://github.com/lsst-uk/lasair-lsst/pull/80)
   - [x]  b. Can delete old cutouts by MJD
    - [x] c. Make and run test to measure speed vs CephFS

- [ ]  2. Performance evaluation -- [use the plan](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3119218729/Performance+Testing+Plan), [results here](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3292004357)
    - [ ] a. Kafka, Ingest, Sherlock, Filter
    - [ ] b. Does the architecture achieve scalability?
    
- [x] 3. Forced photometry on the ZTF system
    - [x] a. [Store new records in Cassandra](https://github.com/lsst-uk/lasair4/pull/204) - All FP being stored in Cassandra
    - [x] b. Need to expose on web with new plot (@thespacedoctor ?)
    
- [ ] 4. Sherlock
    - [x] a. Upgrade code and add DELVE catalogue  - see https://github.com/lsst-uk/lasair-lsst/issues/43
    - [ ] b. Add DELVE catalogue ( @thespacedoctor and @genghisken)

- [x] 5. Build a “marshal notebook”
    - [x] a. Users can eyeball outputs from their filters with veto/favourites.  See [video](https://youtu.be/sgH5cQk-TDU) and [instructions](https://github.com/lsst-uk/lasair-examples/tree/main/notebooks/marshall)
    - [x] b. [Beta test ](https://github.com/lsst-uk/lasair-examples/tree/main/notebooks/marshall)
   
- [ ] 6. New alert distribution from USDF
    - [ ] a. Measure transatlantic speed when available
    
- [x]  7. Active watchlist/watchmap/filter refreshing
    - [x] a. [Alter table to have expiry date, email warning, change to inactive](https://app.zenhub.com/workspaces/lasair-62fcaf02d9b97057d4456a7b/issues/gh/lsst-uk/lasair4/200)
    - [x] b. [speed up watch list crossmatching](https://github.com/lsst-uk/lasair-lsst/issues/6)
   
- [ ] 8. start to build GW alerts infrastructure
    - [ ] a. inherits from more general MMA infrastructure

- [x] 9. [Ingesting 6-filter DP0.2](https://github.com/lsst-uk/lasair-lsst/tree/main/utility/features/DP02) NEW for Cycle-9 

 
Note:  if any items are left over from previous cycle then these are shown as tickets below

**Comment by tms-epcc** [comment]
10/JAN/23
- Marshall notebook 
- Beta test: 6 testers contacted and feedback collected.
- Notebook is now in Lasair examples

**Comment by tms-epcc** [comment]
31/JAN/24
- 1.b. no cutouts in DP0.2 so no progress on this 
- 1.c. now implemented asynchronously and much quicker - @RoyWilliams will supply a PR or similar
- 3.b. now exposed on the web for ZTF code base, 
     - still needs to be done for the LSST codebase ( @thespacedoctor and @RoyWilliams to discuss)
- 4. a. need answers from QUB on state of this 
- 6. Still waiting for this 
- 9. Now know how to tackle this

**Comment by tms-epcc** [comment]
14/FEB/24
@RoyWilliams reported that 
1) b) can delete old cutouts by MJD  **DONE**

**Comment by tms-epcc** [comment]
28/FEB/24 
- At Lasair meeting,  Roy explained that  3. b) is now done hence 
"3. Forced photometry on the ZTF system" is now all done.
