### ISSUE TITLE
Lasair Cycle-10 Apr'24 to Sept'24

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lasair-project-management#312]
As taken from [Lasair Cycle-10 wiki planning page](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3470262274/Lasair+Cycle+10+plan)
See also notes from [24/APR/24](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3489267713/24+April+2024) and [08/MAY/24](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3504865282/8+May+2024) Lasair fortnightly meetings.

Cycle 10 begins at the start of April 2024 (PM58) and finishes at the end of September 2024 (PM63). 

In order of priority, the Activities, deliverables and milestones agreed as due in this cycle 

- [x]  1.  Deploy Lasair-LSST
   - [x] a. Release stable, non-dev system to allow user interaction 
   - [x] b. Declare Lasair version 6 for deliverable end April

- [ ] 2. Performance evaluation, Testing, and Quality -- [use the plan](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3119218729)
  - [ ] a. Continue with monitoring processing
 
- [x] 3. Integrate simulated alert distribution from USDF
    - [x] a. Measure transatlantic speed ( @gpfrancis )
    - [x] b.  Implement new LSST schema ( @RoyWilliams )
   
- [x] 4. Complete GW alerts infrastructure

- [x] 5. Modify Lasair to be effective for Adler
    - [x] a. Build new Kafka stream with SS and cutouts
   - [x] b. Build new tables in Cassandra and filling them

- [ ] 6. Update Sherlock ( @thespacedoctor )
    - [ ] a. Ingest Delve catalogues ( @thespacedoctor )
    - [ ] b. Ingest Gaia catalogues (@genghisken)

- [ ] 7. Integrate new lightcurve features into Lasair
    - [ ] a. Fastfinder ( @genghisken )
    - b. NEEDLE (REMOVED from the Cycle - see 14/AUG/24 comment below)

- [ ] 8. Build Lasair backup strategy (discuss at Lasair SE meeting)

- [x] 9. Submit Lasair paper to Arxiv and then RASTI

- [ ] 10. Build community engagement
    - [ ] a. Analyse the Lasair User Survey
    - [ ] b. Emulate the RSP workshop with a Lasair tutorial
    - [x] c. Create Lasair Users Group
    - [ ] d. Expand the Lasair-DAC connection

 
Note:  if any items are left over from previous cycle then these are shown as tickets below

**Comment by tms-epcc** [comment]
12/JUN/24
- Draft Lasair user group terms of engagement shared with Lasair team

**Comment by tms-epcc** [comment]
31/JUL/24
@RoyWilliams reported 
- activity 3. and its sub-points have been completed, see the [article is in the July'24 newsletter](https://lsst-uk.atlassian.net/wiki/spaces/HOME/pages/3603922946/LSST+UK+Newsletter+46+July+2024#Operations-Rehearsal-for-Lasair%3A-Lessons-learned)
- user group now in place see https://lsst-uk.atlassian.net/wiki/spaces/HOME/pages/3510272001/Lasair+Users+Group

**Comment by tms-epcc** [comment]
14/AUG/24
- Needle is not light curve feature and hence will not be integrated after all. It is an annotator
